### ISSUE TITLE
an error about test

### ISSUE THREAD

**Issue by WuZhongQing** [JeffWang987/DriveDreamer#10]
hi,thanks for your open source, and i meet an error, like:
![image](https://github.com/user-attachments/assets/439922a9-9978-495b-8735-468d9d180a21)

did you meet the same bug when testing video or image?

**Comment by WuZhongQing** [comment]
i have debug that,we should change  founction in tester.py :
![image](https://github.com/user-attachments/assets/edc3360c-dfe0-49b1-9761-2d9d453b95ea)

**Comment by WuZhongQing** [comment]
but after training in nuscenesMini dataset, generate image maybe not so good ：
![image](https://github.com/user-attachments/assets/93230808-d467-4a21-a031-0445de66bd46)

could you provide some advices ?

**Comment by yz996to955** [comment]
Hello, I'm also running this open-source project. Could you tell me approximately how much training resources are needed?

**Comment by WuZhongQing** [comment]
> Hello, I'm also running this open-source project. Could you tell me approximately how much training resources are needed?

i just use nuscenesMini, about 3hours for 20 epochs

**Comment by WuZhongQing** [comment]
> Hello, I'm also running this open-source project. Could you tell me approximately how much training resources are needed?

could you please tell me about your test result, if its not trouble you, you can email me at wuzhongqing22@163.com

**Comment by yz996to955** [comment]
Thank you for your response. I'll get in touch with you.

**Comment by Yang-Jianzhang** [comment]
> but after training in nuscenesMini dataset, generate image maybe not so good ： ![image](https://private-user-images.githubusercontent.com/48616900/383446521-93230808-d467-4a21-a031-0445de66bd46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjYwMTUsIm5iZiI6MTczMDk2NTcxNSwicGF0aCI6Ii80ODYxNjkwMC8zODM0NDY1MjEtOTMyMzA4MDgtZDQ2Ny00YTIxLWEwMzEtMDQ0NWRlNjZiZDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMmJiMWI0NjQxNzkxYTBiYTgyZmU3M2FlNDQ2YmU3NTcyYzkxZjhlZDNlOTBiZDMwMzNmN2Q1NTYwZjY0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.didv3mpckrf4NtEyGlpx0TT6rmp7xX8cb2fD5gxDUmo)
> 
> could you provide some advices ?

I think only training on the mini dataset could not get good generlization. You should use the trained weight from the author, although they are not provided yet.

**Comment by weimengfendou** [comment]
Hello, I'm also running this open-source project. When I run the test set, I always encounter conflicts between float32 and float16.like:
![125](https://github.com/user-attachments/assets/f439de84-2d9f-47ed-a80f-4a0c4e373065)

Could you please tell me if you have ever encountered this kind of situation?

**Comment by nwdxbx** [comment]
@weimengfendou hello, I meet the similar problom. Are you solve it.
RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float

**Comment by BaoziGoodBOY** [comment]
> 但是在 nuscenesMini 数据集中训练后，生成的图像可能不是那么好： ![image](https://github.com/user-attachments/assets/93230808-d467-4a21-a031-0445de66bd46)
> 
> 您能提供一些建议吗？

Hello, during the inference process, the generated images look like this. Have you encountered this issue before?

![Image](https://github.com/user-attachments/assets/d3f90958-6671-4434-a10e-9668c8c77c93)

**Comment by liudun226296** [comment]
May I ask what caused this error during the first phase of testing?
[2025-04-19 15:50:13,869] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-04-19 15:50:13,889] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 86.95it/s]
Expected types for unet: (<class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'>,), got <class 'dreamer_models.models.unet.unet_2d_condition.UNet2DConditionModel'>.
You have disabled the safety checker for <class 'dreamer_models.pipelines.control.pipeline_stable_diffusion_control.StableDiffusionControlPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
An error occurred while trying to fetch /home/ld/projects/drivedreamer/exp/drivedreamer-img_sd15_corners_hdmap_res448/models/checkpoint_epoch_9_step_25173/drivedreamer_ema: Error no file named diffusion_pytorch_model.safetensors found in directory /home/ld/projects/drivedreamer/exp/drivedreamer-img_sd15_corners_hdmap_res448/models/checkpoint_epoch_9_step_25173/drivedreamer_ema.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 86.30it/s]
Expected types for unet: (<class 'diffusers.models.unets.unet_2d_condition.UNet2DConditionModel'>,), got <class 'dreamer_models.models.unet.unet_2d_condition.UNet2DConditionModel'>.
You have disabled the safety checker for <class 'dreamer_models.pipelines.control.pipeline_stable_diffusion_control.StableDiffusionControlPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
An error occurred while trying to fetch /home/ld/projects/drivedreamer/exp/drivedreamer-img_sd15_corners_hdmap_res448/models/checkpoint_epoch_9_step_25173/drivedreamer_ema: Error no file named diffusion_pytorch_model.safetensors found in directory /home/ld/projects/drivedreamer/exp/drivedreamer-img_sd15_corners_hdmap_res448/models/checkpoint_epoch_9_step_25173/drivedreamer_ema.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
2025-04-19 15:50:16,156 Config:
{'dataloaders': {'test': {'batch_size_per_gpu': 1,
                          'data_or_config': '/home/mech_disk1/data/ld/nuscenes_convert/v1.0-mini/cam_all_val/v0.0.2',
                          'num_workers': 0,
                          'transform': {'dd_name': 'image_hdmap',
                                        'default_prompt': 'a realistic driving '
                                                          'scene.',
                                        'dst_size': 224,
                                        'is_train': False,
                                        'max_objs': 50,
                                        'mode': 'long',
                                        'pos_name': 'corner',
                                        'prompt_name': 'sd',
                                        'random_choice': False,
                                        'type': 'DriveDreamerTransform'}},
                 'train': {'batch_size_per_gpu': 2,
                           'data_or_config': '/home/mech_disk1/data/ld/nuscenes_convert/v1.0-mini/cam_all_train/v0.0.2',
                           'num_workers': 1,
                           'sampler': {'type': 'DefaultSampler'},
                           'transform': {'dd_name': 'image_hdmap',
                                         'default_prompt': 'a realistic '
                                                           'driving scene.',
                                         'dst_size': 224,
                                         'is_train': True,
                                         'max_objs': 50,
                                         'mode': 'long',
                                         'pos_name': 'corner',
                                         'prompt_name': 'sd',
                                         'random_choice': True,
                                         'type': 'DriveDreamerTransform'}}},
 'launch': {'deepspeed_config': None,
            'distributed_type': None,
            'gpu_ids': [0, 1],
            'num_machines': 1},
 'models': {'drivedreamer': {'add_in_channels': 6,
                             'grounding_downsampler_cfg': {'in_dim': 3,
                                                           'mid_dim': 4,
                                                           'out_dim': 6,
                                                           'type': 'GroundingDownSampler'},
                             'noise_scheduler_type': 'DDPMScheduler',
                             'position_net_cfg': {'box_dim': 16,
                                                  'feature_type': 'text_only',
                                                  'in_dim': 768,
                                                  'mid_dim': 512,
                                                  'type': 'PositionNet'},
                             'unet_type': 'UNet2DConditionModel'},
            'pipeline_name': 'StableDiffusionControlPipeline',
            'pretrained': 'runwayml/stable-diffusion-v1-5',
            'weight_path': None,
            'with_ema': True},
 'optimizers': {'lr': 1e-05, 'type': 'AdamW', 'weight_decay': 0.0},
 'project_dir': '/home/ld/projects/drivedreamer/exp/drivedreamer-img_sd15_corners_hdmap_res448',
 'schedulers': {'name': 'constant', 'num_warmup_steps': 100},
 'test': {'guidance_scale': 3.5,
          'mixed_precision': 'fp16',
          'save_dir': '/home/ld/projects/drivedreamer/exp/drivedreamer-img_sd15_corners_hdmap_res448/vis'},
 'train': {'activation_checkpointing': False,
           'checkpoint_interval': 1,
           'checkpoint_total_limit': 10,
           'gradient_accumulation_steps': 1,
           'log_interval': 100,
           'log_with': 'tensorboard',
           'max_epochs': 10,
           'mixed_precision': 'fp16',
           'resume': False,
           'with_ema': True}}
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/run_task.py", line 42, in <module>
[rank0]:     main()
[rank0]:   File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/run_task.py", line 38, in main
[rank0]:     run_tasks(args.config, args.runners)
[rank0]:   File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/run_task.py", line 29, in run_tasks
[rank0]:     runner.test()
[rank0]:   File "/home/ld/projects/drivedreamer/dreamer-train/projects/DriveDreamer/drivedreamer/tester.py", line 118, in test
[rank0]:     output_images = self.model(
[rank0]:   File "/home/ld/anaconda3/envs/drivedreamer/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/ld/projects/drivedreamer/dreamer-models/dreamer_models/pipelines/control/pipeline_stable_diffusion_control.py", line 297, in __call__
[rank0]:     assert False
[rank0]: AssertionError
W0419 15:50:17.307114 140097427166016 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4035 closing signal SIGTERM
E0419 15:50:17.371710 140097427166016 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 4034) of binary: /home/ld/anaconda3/envs/drivedreamer/bin/python
Traceback (most recent call last):
  File "/home/ld/anaconda3/envs/drivedreamer/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ld/anaconda3/envs/drivedreamer/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/home/ld/anaconda3/envs/drivedreamer/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1204, in launch_command
    multi_gpu_launcher(args)
  File "/home/ld/anaconda3/envs/drivedreamer/lib/python3.10/site-packages/accelerate/commands/launch.py", line 825, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/ld/anaconda3/envs/drivedreamer/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/ld/anaconda3/envs/drivedreamer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ld/anaconda3/envs/drivedreamer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/run_task.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-04-19_15:50:17
  host      : Ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4034)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/ld/projects/drivedreamer/./dreamer-train/projects/launch.py", line 35, in <module>
    main()
  File "/home/ld/projects/drivedreamer/./dreamer-train/projects/launch.py", line 32, in main
    launch_from_config(config_path, ','.join(opts.runners))
  File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/launch.py", line 173, in launch_from_config
    launcher.launch('{} --config {} --runners {}'.format(file_path, config_path, runners))
  File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/launch.py", line 157, in launch
    os.remove(self.hostfile_path)
FileNotFoundError: [Errno 2] No such file or directory: '_tmp/2025-04-19-155010_hostfile'

**Comment by liudun226296** [comment]
> > Hello, I'm also running this open-source project. Could you tell me approximately how much training resources are needed?
> 
> i just use nuscenesMini, about 3hours for 20 epochs

Hello, I have also run 20 epochs on the mini dataset. Why didn't I generate the diffusionpytorch_madel.safesensor file in the drivedreamer.ema folder?

**Comment by Shuo-Zhang-code** [comment]
> > > 您好，我也在运行这个开源项目。您能告诉我大约需要多少培训资源吗？
> > 
> > 
> > 我只使用 nuscenesMini，大约 3 小时，持续 20 个 epoch
> 
> 您好，我还在迷你数据集上运行了 20 个 epoch。为什么我没有在 drivedreamer.ema 文件夹中生成 diffusionpytorch_madel.safesensor 文件？

你好，我也没有生成diffusionpytorch_madel.safesensor 文件，我生成后缀名为bin的文件，请问你解决了吗

**Comment by Yiminglii** [comment]
hello，请问怎么直接使用mini数据集进行训练呢，我这边训练数据似乎有问题：
 File "/home/DriveDreamer/dreamer-datasets/dreamer_datasets/datasets/base_dataset.py", line 101, in __getitem__
[rank4]:     data_dict = self.transform(data_dict)
[rank4]:   File "/home/DriveDreamer/dreamer-train/projects/DriveDreamer/drivedreamer/transforms.py", line 67, in __call__
[rank4]:     data_dict = self.pos_transform(data_dict)
[rank4]:   File "/home/DriveDreamer/dreamer-train/projects/DriveDreamer/drivedreamer/transforms.py", line 286, in __call__
[rank4]:     keeps = self.choose_objs(data_dict)
[rank4]:   File "/home/DriveDreamer/dreamer-train/projects/DriveDreamer/drivedreamer/transforms.py", line 211, in choose_objs
[rank4]:     corners = data_dict['corners']
[rank4]: KeyError: 'corners'
是否处理过类似的报错呢？
