### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by Bl1tzcrank** [JeffWang987/DriveDreamer#16]
I ran this code in WIN10 with vscode and face with this bug, i am sure that the I put the file under the configs filepath but it still can't run. Run with cuda 12.1 and python 3.10
————————————————
D:\DriveDreamer-main\DriveDreamer-main> python ./dreamer-train/projects/launch.py --project_name DriveDreamer --config_name drivedreamer-video_sd15_corners_hdmap_res448_f32 --runners drivedreamer.DriveDreamerTester
D:\Anaconda\envs\drivedreamer\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
D:\Anaconda\envs\drivedreamer\lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
D:\DriveDreamer-main\DriveDreamer-main\dreamer-models\dreamer_models\models\drivedreamer\convnext.py:179: UserWarning: Overwriting convnext_tiny in registry with dreamer_models.models.drivedreamer.convnext.convnext_tiny. This 
is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def convnext_tiny(pretrained=False, in_22k=False, **kwargs):
D:\DriveDreamer-main\DriveDreamer-main\dreamer-models\dreamer_models\models\drivedreamer\convnext.py:189: UserWarning: Overwriting convnext_small in registry with dreamer_models.models.drivedreamer.convnext.convnext_small. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def convnext_small(pretrained=False, in_22k=False, **kwargs):
D:\DriveDreamer-main\DriveDreamer-main\dreamer-models\dreamer_models\models\drivedreamer\convnext.py:199: UserWarning: Overwriting convnext_base in registry with dreamer_models.models.drivedreamer.convnext.convnext_base. This 
is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def convnext_base(pretrained=False, in_22k=False, **kwargs):
D:\DriveDreamer-main\DriveDreamer-main\dreamer-models\dreamer_models\models\drivedreamer\convnext.py:209: UserWarning: Overwriting convnext_large in registry with dreamer_models.models.drivedreamer.convnext.convnext_large. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def convnext_large(pretrained=False, in_22k=False, **kwargs):
D:\DriveDreamer-main\DriveDreamer-main\dreamer-models\dreamer_models\models\drivedreamer\convnext.py:219: UserWarning: Overwriting convnext_xlarge in registry with dreamer_models.models.drivedreamer.convnext.convnext_xlarge. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  def convnext_xlarge(pretrained=False, in_22k=False, **kwargs):
D:\Anaconda\envs\drivedreamer\lib\site-packages\transformers\utils\hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Traceback (most recent call last):
  File "D:\DriveDreamer-main\DriveDreamer-main\dreamer-train\projects\launch.py", line 38, in <module>
    main()
  File "D:\DriveDreamer-main\DriveDreamer-main\dreamer-train\projects\launch.py", line 35, in main
    launch_from_config(config_path, ','.join(opts.runners))
  File "D:\DriveDreamer-main\DriveDreamer-main\dreamer-train\dreamer_train\distributed\launch.py", line 171, in launch_from_config
    launcher = Launcher(**config.launch)
  File "D:\DriveDreamer-main\DriveDreamer-main\dreamer-train\dreamer_train\distributed\launch.py", line 61, in __init__
    process = subprocess.run(['which', 'accelerate'], env=env, capture_output=True, text=True)
  File "D:\Anaconda\envs\drivedreamer\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda\envs\drivedreamer\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Anaconda\envs\drivedreamer\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by study-overflow** [comment]
I have the same problem, too. Have you solved this problem?
