### ISSUE TITLE
May I ask what the situation is?

### ISSUE THREAD

**Issue by liudun226296** [JeffWang987/DriveDreamer#17]
Traceback (most recent call last):
  File "/home/ld/projects/drivedreamer/./dreamer-train/projects/launch.py", line 35, in <module>
    main()
  File "/home/ld/projects/drivedreamer/./dreamer-train/projects/launch.py", line 32, in main
    launch_from_config(config_path, ','.join(opts.runners))
  File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/launch.py", line 173, in launch_from_config
    launcher.launch('{} --config {} --runners {}'.format(file_path, config_path, runners))
  File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/launch.py", line 157, in launch
    os.remove(self.hostfile_path)
FileNotFoundError: [Errno 2] No such file or directory: '_tmp/2024-12-03-095059_hostfile'

**Comment by ruiqi-song** [comment]
how you solve this issue?

**Comment by study-overflow** [comment]
how you solve this issue?
