### ISSUE TITLE
The code can't create hostfile file correctly

### ISSUE THREAD

**Issue by Bl1tzcrank** [JeffWang987/DriveDreamer#20]
```
W1206 18:53:57.353000 18802 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 18835 closing signal SIGTERM
W1206 18:53:57.354000 18802 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 18836 closing signal SIGTERM
W1206 18:53:57.354000 18802 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 18837 closing signal SIGTERM
W1206 18:53:57.354000 18802 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 18839 closing signal SIGTERM
W1206 18:53:57.354000 18802 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 18840 closing signal SIGTERM
W1206 18:53:57.354000 18802 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 18841 closing signal SIGTERM
W1206 18:53:57.355000 18802 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 18842 closing signal SIGTERM
E1206 18:53:57.387000 18802 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 3 (pid: 18838) of binary: /home/chacha/anaconda3/envs/drive/bin/python
Traceback (most recent call last):
  File "/home/chacha/anaconda3/envs/drive/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/chacha/anaconda3/envs/drive/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/chacha/anaconda3/envs/drive/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/home/chacha/anaconda3/envs/drive/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/chacha/anaconda3/envs/drive/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/chacha/anaconda3/envs/drive/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/chacha/anaconda3/envs/drive/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

/home/drive/DriveDreamer-main/DriveDreamer-main/dreamer-train/dreamer_train/distributed/run_task.py FAILED
```
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-06_18:53:57
  host      : DESKTOP-EJP3C2O.localdomain
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 18838)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```
Traceback (most recent call last):
  File "/home/drive/DriveDreamer-main/DriveDreamer-main/./dreamer-train/projects/launch.py", line 35, in <module>
    main()
  File "/home/drive/DriveDreamer-main/DriveDreamer-main/./dreamer-train/projects/launch.py", line 32, in main
    launch_from_config(config_path, ','.join(opts.runners))
  File "/home/drive/DriveDreamer-main/DriveDreamer-main/dreamer-train/dreamer_train/distributed/launch.py", line 175, in launch_from_config
    launcher.launch('{} --config {} --runners {}'.format(file_path, config_path, runners))
  File "/home/drive/DriveDreamer-main/DriveDreamer-main/dreamer-train/dreamer_train/distributed/launch.py", line 159, in launch
    os.remove(self.hostfile_path)
FileNotFoundError: [Errno 2] No such file or directory: '_tmp/2024-12-06-185351_hostfile'
```

When the code running, this code will create a config file and a hostfile file with timestamps, but the hostfile can't create correctly.

**Comment by dq0803** [comment]
Hi~ I have the same error, did you solve it?

**Comment by weimengfendou** [comment]
It's possible that you forgot to modify some path details in the file drivedreamer-img_sd15_corners_hdmap_res448.py. I remember I also encountered this issue, and after modifying the details in this file and importing some pre-trained weights, it was able to run.

**Comment by Bl1tzcrank** [comment]
> It's possible that you forgot to modify some path details in the file drivedreamer-img_sd15_corners_hdmap_res448.py. I remember I also encountered this issue, and after modifying the details in this file and importing some pre-trained weights, it was able to run.
I change the exp_dir, test_data and train_data but it still don't work, can you tell me more about the details

**Comment by Bl1tzcrank** [comment]
> It's possible that you forgot to modify some path details in the file drivedreamer-img_sd15_corners_hdmap_res448.py. I remember I also encountered this issue, and after modifying the details in this file and importing some pre-trained weights, it was able to run.

I change the exp_dir, test_data and train_data but it still don't work, can you tell me more about the details

**Comment by weimengfendou** [comment]
In the ENV.py file, you need to modify the paths for `os.environ['TORCH_HOME']`, `os.environ['TRANSFORMERS_CACHE']`, `os.environ['HUGGINGFACE_HUB_CACHE']`, and `os.environ['XDG_CACHE_HOME']`. 
Then, you need to download the pre-trained weights such as `models--openai--clip-vit-large-patch14` and `models--runwayml--stable-diffusion-v1-5`. 
Since my server does not have access to the internet, I first downloaded them locally and then transferred them to the server. 
I hope this helps you.

**Comment by nwdxbx** [comment]
@weimengfendou Hello, I need the pre-trained weights. can you tell me the download links, Thanks!

**Comment by nwdxbx** [comment]
@weimengfendou  I have found the pre-trained weights, Thanks!

**Comment by Tangme10** [comment]
> [@weimengfendou](https://github.com/weimengfendou) 我已经找到了预先训练的权重，谢谢！

can u give me an example of config

**Comment by BaoziGoodBOY** [comment]
> In the ENV.py file, you need to modify the paths for `os.environ['TORCH_HOME']`, `os.environ['TRANSFORMERS_CACHE']`, `os.environ['HUGGINGFACE_HUB_CACHE']`, and `os.environ['XDG_CACHE_HOME']`. Then, you need to download the pre-trained weights such as `models--openai--clip-vit-large-patch14` and `models--runwayml--stable-diffusion-v1-5`. Since my server does not have access to the internet, I first downloaded them locally and then transferred them to the server. I hope this helps you.

Hello,i want to ask a question about i  have done download pretrianed weights,but an error happened"OSError: Error no file named config.json found in directory /home/qw/Baozi/DriveDreamer-main/models/huggingface/models--runwayml--stable-diffusion-v1-5.",how can i solve this problem,thanks for ur help

**Comment by cxiangood** [comment]
> [@weimengfendou](https://github.com/weimengfendou) I have found the pre-trained weights, Thanks!

Can you share it to me? Thanks.

**Comment by nwdxbx** [comment]
> > [@weimengfendou](https://github.com/weimengfendou) I have found the pre-trained weights, Thanks!
> 
> Can you share it to me? Thanks.

This models you can find at https://huggingface.co/ .
for example , models--runwayml--stable-diffusion-v1-5's address is https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5.

**Comment by cxiangood** [comment]
> > > [@weimengfendou](https://github.com/weimengfendou) I have found the pre-trained weights, Thanks!
> > 
> > 
> > Can you share it to me? Thanks.
> 
> This models you can find at https://huggingface.co/ . for example , models--runwayml--stable-diffusion-v1-5's address is https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5.

Thanks for the reply, but I don't think it's a model weight, it's a dependency.

**Comment by Shuo-Zhang-code** [comment]
请问在https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5，我们需要下哪个模型，谢谢

**Comment by Shuo-Zhang-code** [comment]
![Image](https://github.com/user-attachments/assets/9f187fd1-5615-4891-bf9b-a63cbe811700)

![Image](https://github.com/user-attachments/assets/9b915378-5480-4322-b2ff-cba082a7253e)

请问我完成训练了，但还是没法正确创建hostfile文件，这是怎么回事

**Comment by JumpFlying** [comment]
> > In the ENV.py file, you need to modify the paths for `os.environ['TORCH_HOME']`, `os.environ['TRANSFORMERS_CACHE']`, `os.environ['HUGGINGFACE_HUB_CACHE']`, and `os.environ['XDG_CACHE_HOME']`. Then, you need to download the pre-trained weights such as `models--openai--clip-vit-large-patch14` and `models--runwayml--stable-diffusion-v1-5`. Since my server does not have access to the internet, I first downloaded them locally and then transferred them to the server. I hope this helps you.
> 
> Hello,i want to ask a question about i have done download pretrianed weights,but an error happened"OSError: Error no file named config.json found in directory /home/qw/Baozi/DriveDreamer-main/models/huggingface/models--runwayml--stable-diffusion-v1-5.",how can i solve this problem,thanks for ur help

@BaoziGoodBOY  Hello, I encountered the same problem. Have you solved it? Thanks.
