### ISSUE TITLE
How can I solve this error that occurred during training?

### ISSUE THREAD

**Issue by liudun226296** [JeffWang987/DriveDreamer#24]
[2024-12-24 11:17:01,290] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 91055) of binary: /home/ld/Anaconda/envs/drivedreamer/bin/python
Traceback (most recent call last):
  File "/home/ld/Anaconda/envs/drivedreamer/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ld/Anaconda/envs/drivedreamer/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/ld/Anaconda/envs/drivedreamer/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/home/ld/Anaconda/envs/drivedreamer/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/ld/Anaconda/envs/drivedreamer/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/ld/Anaconda/envs/drivedreamer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ld/Anaconda/envs/drivedreamer/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/run_task.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-12-24_11:17:01
  host      : boys
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 91056)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 91056
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-24_11:17:01
  host      : boys
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 91055)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 91055
============================================================
Traceback (most recent call last):
  File "/home/ld/projects/drivedreamer/./dreamer-train/projects/launch.py", line 39, in <module>
    main()
  File "/home/ld/projects/drivedreamer/./dreamer-train/projects/launch.py", line 36, in main
    launch_from_config(config_path, ','.join(opts.runners))
  File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/launch.py", line 174, in launch_from_config
    launcher.launch('{} --config {} --runners {}'.format(file_path, config_path, runners))
  File "/home/ld/projects/drivedreamer/dreamer-train/dreamer_train/distributed/launch.py", line 158, in launch
    os.remove(self.hostfile_path)
FileNotFoundError: [Errno 2] No such file or directory: '_tmp/2024-12-24-103306_hostfile'

**Comment by study-overflow** [comment]
I have the same issue, too. Have you solved this problem?

**Comment by BaoziGoodBOY** [comment]
you can learn from #20 problem
